version: "3"

services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
      args:
          - http_proxy=${http_proxy}
          - https_proxy=${https_proxy}
          - no_proxy=${no_proxy}
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bcbotuser
      - POSTGRES_PASSWORD=bcbotuser_password
      - POSTGRES_DB=bcbot
  celery-broker:
    image: redis:6.0.1-alpine3.11
  app:
    build: 
      context: app
      dockerfile: Dockerfile
      args:
          - http_proxy=${http_proxy}
          - https_proxy=${https_proxy}
          - no_proxy=${no_proxy}
    restart: unless-stopped
    ports:
      - "8085:8000"
    volumes:
      - ./volumes/app:/home/bcbot/
    depends_on:
      - db
      - celery-broker
  celery-worker:
    build:
      context: celery
      dockerfile: Dockerfile
      args:
          - http_proxy=${http_proxy}
          - https_proxy=${https_proxy}
          - no_proxy=${no_proxy}
    restart: unless-stopped
    tty: true
    volumes:
      - ./volumes/app:/home/bcbot/
    environment:
      - CELERY_RUNMODE="worker"
    depends_on:
      - db
      - app
      - celery-broker
  celery-beat:
    build:
      context: celery
      dockerfile: Dockerfile
      args:
          - http_proxy=${http_proxy}
          - https_proxy=${https_proxy}
          - no_proxy=${no_proxy}
    restart: unless-stopped
    tty: true
    volumes:
      - ./volumes/app:/home/bcbot/
    environment:
      - CELERY_RUNMODE="beat"
    depends_on:
      - db
      - app
      - celery-broker

volumes:
  postgres_data: